spring.application.name=tutorvirtual-backend

# ===== DATASOURCE (SUPABASE - SESSION POOLER) =====
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.abbggyhiwkrrasxjvvms
spring.datasource.password=gDbp8GB69FRuDU4T
spring.datasource.driver-class-name=org.postgresql.Driver


# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Dialect NO es obligatorio, Hibernate lo detecta solo
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===== HIKARI (OBLIGATORIO PARA POOLER) =====
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# ===== SSL (SUPABASE OBLIGATORIO) =====
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require

# Multipart
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ===== GEMINI =====
gemini.api.key=AIzaSyCP3Hi3KrEzITIg3PkUlltTAR8Dj7DEfZY
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?




